company/urls.py
from django.urls import path
from .views import company, sign_up, contact, home

app_name = 'company'

urlpatterns = [ 
    path('about/', company, name='about'),
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('signup/', sign_up, name='signup'),
    ]

menu/urls.py
from django.urls import path
from .views import menu, albom

app_name = 'menu'

urlpatterns = [
    path('menu/', menu,  name='menu_page'),
    path('albom/', albom,  name='albom'),
    
]

project/urls.py
from django.contrib import admin
from django.urls import path, include # add this
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('company.urls', namespace="company")), # add this
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('menu.urls', namespace="menu")), # add this
    path('api-auth/', include('rest_framework.urls')),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.

class Company(models.Model):
    name = models.CharField(_("Name"), max_length=200)
    sub_title = models.CharField(_("Sub titl"), max_length=200)
    description = models.TextField(_("Description"),)
    address = models.TextField(_("Address") ,max_length=1000)
    phone = models.CharField(_("Phone"), max_length=200)
    email = models.EmailField(_("Email"), max_length=200)
    logo = models.ImageField(_("Logo"), upload_to='company_logo/', null=True, blank=True)
    location = models.URLField(_("location"), blank=True, null=True)
    fb_link = models.URLField(_("facebook link"), blank=True, null=True)
    ins_link = models.URLField(_("instagram link"), blank=True, null=True)
    tw_link = models.URLField(_("tweeter link"), blank=True, null=True)
 
    def __str__(self):
        return self.name
    
class Users(models.Model):
    user = models.OneToOneField(User, verbose_name=_("user"), on_delete=models.CASCADE)
    phone = models.CharField(_("Phone"), max_length=200)
    city = models.CharField(max_length=20)


    def __str__(self):
        return str(self.user)




@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Users.objects.create(user=instance)

menu/models.py
from django.db import models
from django.utils.translation import gettext as _

# Create your models here.
CATEGPRY_CHOICES = (
    ('Drinks', 'Drinks'),
    ('Drip coffe', 'Drip coffe'),
    ('Cold coffe', 'Cold coffe'),
    ('Hot coffe', 'Hot coffe'),
    ('Extra', 'Extra'),
    ('Matcha', 'Matcha'),
    ('Sandwiches', 'Sandwiches'),
)

class Menu(models.Model):
    name = models.CharField(_("Name"), max_length=100)
    price = models.IntegerField(_("Price"),)
    type = models.CharField(_("Item type"),choices=CATEGPRY_CHOICES, max_length=100)
    
    def __str__(self):  
        return self.name
    

class Albom(models.Model):
    items = models.ForeignKey(Menu, verbose_name=_("MenuImages"), on_delete=models.CASCADE)
    imges = models.ImageField(_("Images"), upload_to='images/')
    
    def __str__(self):
        return str(self.items)
    


    

company/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignupForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

company/views.py
from django.shortcuts import render
from .models import *
from .forms import SignupForm
from django.shortcuts import redirect
# Create your views here.

def company(request):
    company = Company.objects.all()

    context = {
        'company':company,
    }
    return render(request, 'information/about.html', context)

def contact(request):
    company = Company.objects.last()

    context = {
        'company':company,
    }
    return render(request, 'information/contact.html', context)

def home(request):
    company = Company.objects.all()

    context = {
        'company':company,
    }
    return render(request, 'information/home.html', context)


    
def sign_up(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            phone = request.POST.get('phonenumber')
            city = request.POST.get('city')

            myform = form.save()
            users = Users.objects.get(user__username=username)  
            users.phone = phone
            users.city = city
            users.save()
            

            # # send email
            # send_mail(
            #     subject= 'Greeny Activate Your Account',
            #     message=f"user this code {profile.code} to activate your acount", 
            #     from_email='mahmoudtino56@gmail.com', 
            #     recipient_list= [email],
            #     fail_silently=False
            # )
            return redirect(f"/accounts/login/")

    else:
        form = SignupForm()
    return render(request, 'registration/signup.html', {"form":form} )

menu/views.py
from django.shortcuts import render
from .models import Menu, Albom
# Create your views here.

def menu(request):
    menu = Menu.objects.all()
    return render(request, 'menu/menu.html', {'menu': menu})

def albom(request):
    albom = Albom.objects.all()
    return render(request, 'menu/albom.html', {'albom': albom})

company/templates/information/about.html
{% extends 'base.html' %}
{% block body %}

    <!-- start who are we section -->
    <section class="who-are-we">
        <h1 class="text-center">You Need to Hear it From Us?</h1>
        <h2 class="text-center">Ok..</h2>
        <br>
        <div class="col-7 who-p">
            <p>
                We are a Saudi Brand inspired by the heritage and lifestyle of the Japanese
                 Culture, we provide an entertainment
                and social space to our clients, with the highest quality drinks and treats,
                 and continuous surprises on the shelves!
                joy is our native language, and culture is the medium in which we communicate
                 and deliver our ideas through.
                We are minimalists, we help our clients in feeling less stressful and more joyful,
                 we are also detail-oriented, we
                never miss a detail, but don’t worry, it doesn’t mean that we’ll stalk you, but we’ll
                 be able to recognize your laugh,
                distinguish your smile, and feel the joy in your heart if you walked through our doors,
                 we are consistent in what we
                deliver to our clients, as consistency is a way to build a long-term connection with our
                 communities, and
                communities are the essence of our work, they are why we are here from the first place!
            </p>
        </div>
    </section>
    <!-- end who are we section -->

    <!-- start Values section -->
    <section class="value">
        <h1 class="text-center">
            What Values Influences Us ?
        </h1>
        <br>
        <br>
        <div class="container text-center">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-3">
                    <h3>Sustainability</h3>
                    <p>
                        We choose environment-friendly
                        products, and we sustain a long-term
                        relationships with our customers.
                    </p>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <h3>Culture</h3>
                    <p>
                        We offer a multi-cultural experience
                        that can change the way people
                        perceive life and view the world around
                        them.
                    </p>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <h3>Connection</h3>
                    <p>
                        We make people connect with themselves
                        and their surroundings by connecting
                        with others. We call it the bonding
                        experiment.
                    </p>
                </div>
                <div class="col-12 col-md-6 col-lg-3">
                    <h3>Value Added</h3>
                    <p>
                        We care about the messages being
                        communicated and values being delivered within
                        our services and our through our products for all
                        involved parties.
                    </p>
                </div>
            </div>
        </div>
    </section>
    <!-- end Values section -->

    <!-- start Provide section -->
    <section class="who-are-we">
            <h1 class="text-center">What Do We Exactly Provide in Janken?</h1>
            <br>
            <div class="col-7 who-p">
                <p>
                    In simple words, we provide you an entertainment and social space
                    where you can disconnect from the digital world
                    and connect to the real world through playing and engaging with
                    your surroundings, and we provide you with a unique
                    selections of food and beverages that can make you engage in
                    the moment with your five senses.
                    Disconnecting from the virtual lives and engaging in a real
                    social experiment can make a difference, and the secret is in
                    the “endorphins hormones “, which is “our favorite hormone”!
                    It releases all the stress and activates parts in the brain
                    where you can feel your creative self again, and become more
                    joyful, if you really engaged in the moment.
                </p>
            </div>
    </section>
    <!-- end Provide section -->

    <!-- start main lines section -->
    <section>
        <h1 class="text-center">What Are Our Two Main Lines of Service?</h1>
        <br>
        <br>
        <div class="container text-center">
            <div class="row">
                <div class="col-12 col-md-12 col-lg-6">
                    <h3>Entertainment — The Joy Line</h3>
                    <div class="col-11">
                        <p>
                            Let’s start with definitions, to entertain is to make
                            people feel a certain amount of emotions.
                            In our shelves, there are variety of board games, card
                            games, and kinetic games that will make you feel
                            yourself once again.
                        </p>
                    </div>
                </div>
                <div class="col-12 col-md-12 col-lg-6">
                    <h3>Food and Beverage — The Excitement Line</h3>
                    <div class="col-11">
                        <p>
                            To be excited is to not know what to expect, we all like the
                            anticipation of what’s going to be serve.
                            In our bar, there are variety of snacks and beverages options, even for
                            non-coffee lovers; that’ll make you always excited for more.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- end main lines section -->
    <br>
    <br>
    <br>
    <br>
    <!-- start Work section -->
    <section>
        <h1 class="text-center">What Do We Work on Everyday?</h1>
        <br>
        <div class="col-7 who-p">
            <p>
                We are dreamers, creators, and innovators.
                We want to leave an impact on the society and make a change, it might sound cliche, but it is real.
                Our spaces can be utilized in various of ways, and our shelves are always waiting for something new, we
                welcome you inside Janken at all times, and we come to you with all the passion we have within us, to fill your
                clients with it too.
            </p>
            <br>
            <p>
                And we can’t define ourselves just yet.. as we are shaping ourselves as the days go by.
                We believe that our journey will take us where we want to go, so how about you share this journey with us?
            </p>
        </div>
    </section>
    <!-- end Work section -->
    <br>
    <br>
{% endblock body %}

company/templates/information/contact.html
{% extends 'base.html' %}
{% block body %}
    <!-- start contact section -->
    <section>
        <div style="width: 100%"><iframe width="100%" height="600" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=%D8%A7%D9%84%D9%85%D8%AF%D9%8A%D9%86%D8%A9%20%D8%A7%D9%84%D9%85%D9%86%D9%88%D8%B1%D8%A9+(My%20Business%20Name)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.maps.ie/distance-area-calculator.html">area maps</a></iframe></div>
        <div class="container text-center p-5 social-media">
            <div class="row">
                <div class="col-6 media-link">
                    <a href="{{company.fb_link}}">
                        <i class="fa-brands fa-facebook"></i>
                        Facebook Page
                    </a>
                </div>
                <br>
                <div class="col-6 media-link">
                    <a href="{{company.ins_link}}">
                        <i class="fa-brands fa-linkedin"></i>
                        Linked In
                    </a>
                </div>
                <br>
                <div class="col-6 media-link">
                    <a href="mailto:example@gmail.com">
                        <i class="fa-solid fa-envelope"></i>
                        {{company.email}}
                    </a>
                </div>
                <br>
                <div class="col-6 media-link">
                    <a href="#">
                        <i class="fa-solid fa-phone"></i>
                        {{company.phone}}}
                    </a>
                </div>
            </div>
        </div>
    </section>    
    <!-- end contact section -->

{% endblock body %}

company/templates/information/home.html
{% extends 'base.html' %}
{% load static %}
{% block body %}

    <!-- start hero section -->
    <section>
        <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img src="{% static 'images/01.png' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/02.png' %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                    <img src="{% static 'images/03.png' %}" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
</section>
<!-- end hero section -->

<!-- start about section -->
<section class="about-section">
    <h2 class="text-center about-h2">About <span><b>Janken</b></span></h2>
    <div class="container">
        <div class="col-12 col-lg-12">
            <h3>
                Janken…
            </h3>
            <h3>
                A <b>Culture-Driven</b> Experience
            </h3>
            <br>
            <p>
                Curiosity is the essence of human nature, and we fulfill our curiosity
                by digging more into the concepts we want to learn more
                about, and for us, our interest revolve around the Japanese Culture.
                The Japanese Culture taught us that everything has a meaning, as they 
                have a concept called “Ikiagi”, which means “having a
                passion that gives value and joy of life”, the “Ikiagi” concept blew our 
                minds, and we wanted to inject it into our work; to
                create something of value to our clients, partners, and even for ourselves.
            </p>
            <br>
            <p>
                <u>But you might ask, from all names and cultural symbols, why Janken?</u>
                <br>
                Janken “じゃんけん” is a cultural keystone, it is a Japanese term that describes 
                the worldwide famous game
                “Rock, Scissors, And Paper”.
                We all know that making decisions can be challenging sometimes, 
                but challenges can be less stressful and more fun if it is
                within a context of a game!
                With “Rock, Scissors, Paper” simple mechanics, you can turn a situation 
                into a competitive and fun experience, you can build
                relationships with people around you, and you can create memories that 
                last for a lifetime.
                And that’s Janken, that’s who we are!
            </p>
        </div>
    </div>
</section>
<!-- end about section -->

<!-- start companies section -->
<section class="companies container">
<div class="row">
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_1610.JPG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3155.JPG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3291.PNG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3328.PNG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3359.JPG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3821.PNG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3910.JPG" alt="">
    </div>
    <div class="col-12 col-md-4 col-lg-3">
        <img src="image/IMG_3911.JPG" alt="">
    </div>
</div>
</section>
<!-- end companies section -->

{% endblock body %}

menu/templates/menu/albom.html
{% extends 'base.html' %}
{% block body %}
  <!-- start Albom section -->
  <section class="albom">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image/صور جانكن/نسخة من 1.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 3.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 4.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 4(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 7.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 8(2).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 9.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 9(1).png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 10.png" alt="">
            </div>
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 11.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 12.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 14.png" alt="">
            </div>  
            <div class="col-12 col-md-6 col-lg-3">
                <img width="300" src="image\صور جانكن\نسخة من 15.png" alt="">
            </div>  
        </div>
    </div>
</section>
<!-- end Albom section -->

{% endblock body %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Janken</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <!-- bootstrsp -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel='stylesheet' type='text/css' media='screen' href='{% static 'style.css' %}'>


</head>
<body style="overflow-x: hidden;">

    <!-- start nav -->
    <header class="container">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="{{company.logo.url}}" width="70" alt="">
                </a>
                <button style="border: none; outline: none;" class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'company:home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company:about' %}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'menu:menu_page' %}">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'company:contact' %}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'menu:albom' %}">Albom</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'company:signup' %}">Sign Up</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" href="{% url 'login' %}">Log In</a>
                        </li>
                    </ul>
                </div>
                </div>
            </nav>
    </header>
    <!-- end nav -->
{% block body %}{% endblock body %}
    <!-- start footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 col-lg-4">
                    <img src="image/لوقو جانكن PNG/Copy of Artboard 2-8.png" width="200" alt="">
                    <p class="footer-p">{{context.sub_title}}</p>
                </div>
                <div class="col-12 col-md-6 col-lg-4">
                    <ul>
                        <li>{{company.phone}}</li>
                        <li>{{company.email}}</li>
                        <li>{{company.address}}</li>
                    </ul>
                </div>
                <div class="col-12 col-md-6 col-lg-4 footer-links">
                    <a href="menu.html">menu</a>
                    <br>
                    <br>
                    <a href="{% url 'login' %}">log in</a>
                </div>
            </div>
        </div>
    </footer>
    <!-- end footer -->

<!-- bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
<script src="{% static 'script.js' %}"></script>
</body>
</html>